stages:
  - install
  - test
  - build

# =====================
# FRONTEND
# =====================

frontend_install:
  stage: install
  image: node:20
  script:
    - cd frontend
    - npm install

frontend_test:
  stage: test
  image: node:20
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run typecheck
    - npm run test:run

frontend_build:
  stage: build
  image: node:20
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build

# =====================
# BACKEND
# =====================

backend_test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn test

backend_build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn clean package