-- =============================================================================
-- ETL CONTROL TABLES
-- =============================================================================

-- Watermark table to track ETL progress and enable incremental loads
CREATE TABLE analytics.etl_watermark (
    watermark_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    
    pipeline_name VARCHAR(100) NOT NULL,
    source_table VARCHAR(100) NOT NULL,
    
    last_processed_transaction_id BIGINT,
    last_processed_authorization_datetime TIMESTAMP,
    
    last_successful_run_at TIMESTAMP,
    current_run_started_at TIMESTAMP,
    
    status VARCHAR(30) NOT NULL DEFAULT 'IDLE', -- IDLE, RUNNING, SUCCESS, FAILED
    error_message VARCHAR(1000),
    
    rows_processed INT DEFAULT 0,
    rows_loaded INT DEFAULT 0,
    
    CONSTRAINT pk_etl_watermark PRIMARY KEY (watermark_id),
    CONSTRAINT uq_etl_watermark_pipeline UNIQUE (pipeline_name, source_table),
    CONSTRAINT ck_etl_watermark_status CHECK (status IN ('IDLE', 'RUNNING', 'SUCCESS', 'FAILED'))
);

-- ETL run log for auditing and troubleshooting
CREATE TABLE analytics.etl_run_log (
    run_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    
    pipeline_name VARCHAR(100) NOT NULL,
    job_name VARCHAR(100) NOT NULL,
    
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    
    status VARCHAR(30) NOT NULL, -- STARTED, SUCCESS, FAILED, SKIPPED
    rows_processed INT,
    rows_loaded INT,
    duration_seconds NUMERIC(10, 2),
    
    error_message VARCHAR(1000),
    
    CONSTRAINT pk_etl_run_log PRIMARY KEY (run_log_id),
    CONSTRAINT ck_etl_run_log_status CHECK (status IN ('STARTED', 'SUCCESS', 'FAILED', 'SKIPPED'))
);

CREATE INDEX idx_etl_run_log_pipeline_job ON analytics.etl_run_log (pipeline_name, job_name);
CREATE INDEX idx_etl_run_log_started_at ON analytics.etl_run_log (started_at DESC);
