CREATE SCHEMA IF NOT EXISTS analytics;

-- =============================================================================
-- DIMENSION: Date
-- Grain: one row per calendar date
-- =============================================================================
CREATE TABLE analytics.dim_date (
    date_key INT NOT NULL, -- YYYYMMDD
    full_date DATE NOT NULL,
    day_number INT NOT NULL,
    month_number INT NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    quarter_number INT NOT NULL,
    year_number INT NOT NULL,
    is_weekend CHAR(1) NOT NULL,

    CONSTRAINT pk_dim_date PRIMARY KEY (date_key),
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date),
    CONSTRAINT ck_dim_date_is_weekend CHECK (is_weekend IN ('Y', 'N'))
);

-- =============================================================================
-- DIMENSION: Region
-- Source: public.regions
-- =============================================================================
CREATE TABLE analytics.dim_region (
    region_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_region_code VARCHAR(30) NOT NULL,
    region_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),

    CONSTRAINT pk_dim_region PRIMARY KEY (region_key),
    CONSTRAINT uq_dim_region_source_code UNIQUE (source_region_code)
);

-- =============================================================================
-- DIMENSION: Country - SCD Type 2
-- Source: public.countries + public.regions
-- =============================================================================
CREATE TABLE analytics.dim_country (
    country_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_country_code CHAR(2) NOT NULL,

    country_name VARCHAR(100) NOT NULL,
    region_code VARCHAR(30) NOT NULL,
    region_name VARCHAR(100),

    effective_from TIMESTAMP NOT NULL,
    effective_to TIMESTAMP,
    is_current CHAR(1) NOT NULL DEFAULT 'Y',
    version_number INT NOT NULL DEFAULT 1,

    CONSTRAINT pk_dim_country PRIMARY KEY (country_key),

    CONSTRAINT ck_dim_country_current CHECK (is_current IN ('Y', 'N')),
    CONSTRAINT ck_dim_country_dates CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT uq_dim_country_version UNIQUE (source_country_code, effective_from)
);

CREATE UNIQUE INDEX uq_dim_country_current ON analytics.dim_country (source_country_code)
WHERE is_current = 'Y';

-- =============================================================================
-- DIMENSION: Client
-- Source: public.clients + public.countries
-- =============================================================================
CREATE TABLE analytics.dim_client (
    client_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_client_id BIGINT NOT NULL,

    client_name VARCHAR(100) NOT NULL,
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR(100),
    region_code VARCHAR(30),

    CONSTRAINT pk_dim_client PRIMARY KEY (client_key),
    CONSTRAINT uq_dim_client_source_id UNIQUE (source_client_id)
);

-- =============================================================================
-- DIMENSION: Merchant - SCD Type 2
-- Source: public.merchants + public.acquiring_partners + public.mcc_codes + public.countries
-- =============================================================================
CREATE TABLE analytics.dim_merchant (
    merchant_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_merchant_id BIGINT NOT NULL,

    merchant_name VARCHAR(150) NOT NULL,

    mcc_code VARCHAR(4) NOT NULL,
    mcc_description VARCHAR(255),

    country_code CHAR(2) NOT NULL,
    country_name VARCHAR(100),
    region_code VARCHAR(30),

    city VARCHAR(100),
    address VARCHAR(255),

    source_acquiring_partner_id BIGINT,
    acquiring_partner_name VARCHAR(100),
    acquiring_partner_type VARCHAR(30),

    effective_from TIMESTAMP NOT NULL,
    effective_to TIMESTAMP,
    is_current CHAR(1) NOT NULL DEFAULT 'Y',
    version_number INT NOT NULL DEFAULT 1,

    CONSTRAINT pk_dim_merchant PRIMARY KEY (merchant_key),

    CONSTRAINT ck_dim_merchant_current CHECK (is_current IN ('Y', 'N')),
    CONSTRAINT ck_dim_merchant_dates CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT uq_dim_merchant_version UNIQUE (source_merchant_id, effective_from)
);

CREATE UNIQUE INDEX uq_dim_merchant_current ON analytics.dim_merchant (source_merchant_id)
WHERE is_current = 'Y';

-- =============================================================================
-- DIMENSION: Card
-- Source: public.cards + public.card_types + public.card_networks + public.banks
-- =============================================================================
CREATE TABLE analytics.dim_card (
    card_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_card_id BIGINT NOT NULL,

    card_product_type VARCHAR(30),

    source_card_type_id BIGINT NOT NULL,
    card_type_name VARCHAR(30) NOT NULL,
    card_type_description VARCHAR(255),

    source_card_network_id BIGINT NOT NULL,
    network_code VARCHAR(30) NOT NULL,
    network_name VARCHAR(100) NOT NULL,

    source_issuer_bank_id BIGINT NOT NULL,
    issuer_bank_name VARCHAR(100) NOT NULL,
    issuer_country_code CHAR(2) NOT NULL,
    issuer_country_name VARCHAR(100),
    issuer_region_code VARCHAR(30),

    CONSTRAINT pk_dim_card PRIMARY KEY (card_key),
    CONSTRAINT uq_dim_card_source_id UNIQUE (source_card_id)
);

-- =============================================================================
-- DIMENSION: Acquiring Partner
-- Source: public.acquiring_partners + public.countries
-- =============================================================================
CREATE TABLE analytics.dim_acquiring_partner (
    acquiring_partner_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_acquiring_partner_id BIGINT NOT NULL,

    partner_name VARCHAR(100) NOT NULL,
    partner_type VARCHAR(30) NOT NULL,

    country_code CHAR(2) NOT NULL,
    country_name VARCHAR(100),
    region_code VARCHAR(30),

    CONSTRAINT pk_dim_acquiring_partner PRIMARY KEY (acquiring_partner_key),
    CONSTRAINT uq_dim_acquiring_partner_source_id UNIQUE (source_acquiring_partner_id),
    CONSTRAINT ck_dim_acquiring_partner_type CHECK (partner_type IN ('BANK', 'PSP'))
);

-- =============================================================================
-- DIMENSION: Interchange Category
-- Source: public.interchange_categories
-- =============================================================================
CREATE TABLE analytics.dim_interchange_category (
    category_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_category_id BIGINT NOT NULL,

    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),

    CONSTRAINT pk_dim_interchange_category PRIMARY KEY (category_key),
    CONSTRAINT uq_dim_interchange_category_source UNIQUE (source_category_id),
    CONSTRAINT uq_dim_interchange_category_name UNIQUE (category_name)
);

-- =============================================================================
-- FACT: Transaction Analysis
--
-- Grain:
-- One row per completed transaction analysis.
--
-- Meaning:
-- One row combines:
-- - original transaction
-- - CURRENT interchange result
-- - OPTIMAL interchange result
-- - optimization saving
--
-- Partitioning:
-- Partitioned by authorization_date_key.
-- =============================================================================
CREATE TABLE analytics.fact_transaction_analysis (
    analysis_fact_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    source_transaction_id BIGINT NOT NULL,
    source_current_result_id BIGINT NOT NULL,
    source_optimal_result_id BIGINT NOT NULL,
    source_optimization_result_id BIGINT NOT NULL,

    authorization_date_key INT NOT NULL,

    client_key BIGINT NOT NULL,
    merchant_key BIGINT NOT NULL,
    card_key BIGINT NOT NULL,
    acquiring_partner_key BIGINT NOT NULL,
    region_key BIGINT NOT NULL,

    current_category_key BIGINT NOT NULL,
    optimal_category_key BIGINT NOT NULL,

    transaction_amount NUMERIC(12, 2) NOT NULL,
    transaction_currency CHAR(3) NOT NULL,
    transaction_channel VARCHAR(30) NOT NULL,
    transaction_mcc_code VARCHAR(4) NOT NULL,
    transaction_status VARCHAR(30) NOT NULL,

    is_3ds_authenticated CHAR(1) NOT NULL,
    clearing_hours NUMERIC(10, 2), -- it stores how long did it take for the transaction to move from authorization to clearing/settlement ex.: value 48 for 48 hours
    clearing_time_condition VARCHAR(30),

    current_fee_percentage NUMERIC(7, 4) NOT NULL,
    current_interchange_fee_amount NUMERIC(12, 2) NOT NULL,

    optimal_fee_percentage NUMERIC(7, 4) NOT NULL,
    optimal_interchange_fee_amount NUMERIC(12, 2) NOT NULL,

    saving_amount NUMERIC(12, 2) NOT NULL,
    saving_percentage NUMERIC(7, 4),

    recommendation_count INT NOT NULL DEFAULT 0,
    top_recommendation_type VARCHAR(50),
    top_recommendation_text VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_fact_transaction_analysis PRIMARY KEY (analysis_fact_id, authorization_date_key),

    CONSTRAINT uq_fact_transaction_analysis_source UNIQUE (source_transaction_id, authorization_date_key),

    CONSTRAINT fk_fact_authorization_date FOREIGN KEY (authorization_date_key) REFERENCES analytics.dim_date (date_key),
    CONSTRAINT fk_fact_client FOREIGN KEY (client_key) REFERENCES analytics.dim_client (client_key),
    CONSTRAINT fk_fact_merchant FOREIGN KEY (merchant_key) REFERENCES analytics.dim_merchant (merchant_key),
    CONSTRAINT fk_fact_card FOREIGN KEY (card_key) REFERENCES analytics.dim_card (card_key),
    CONSTRAINT fk_fact_acquiring_partner FOREIGN KEY (acquiring_partner_key) REFERENCES analytics.dim_acquiring_partner (acquiring_partner_key),
    CONSTRAINT fk_fact_region FOREIGN KEY (region_key) REFERENCES analytics.dim_region (region_key),
    CONSTRAINT fk_fact_current_category FOREIGN KEY (current_category_key) REFERENCES analytics.dim_interchange_category (category_key),
    CONSTRAINT fk_fact_optimal_category FOREIGN KEY (optimal_category_key) REFERENCES analytics.dim_interchange_category (category_key),

    CONSTRAINT ck_fact_transaction_amount CHECK (transaction_amount > 0),
    CONSTRAINT ck_fact_transaction_mcc_code CHECK (transaction_mcc_code ~ '^[0-9]{4}$'),
    CONSTRAINT ck_fact_fee_amounts CHECK (current_interchange_fee_amount >= 0 AND optimal_interchange_fee_amount >= 0 AND saving_amount >= 0),
    CONSTRAINT ck_fact_3ds CHECK (is_3ds_authenticated IN ('Y', 'N')),
    CONSTRAINT ck_fact_clearing_condition CHECK (clearing_time_condition IS NULL OR clearing_time_condition IN ('LTE_24H', 'GT_24H'))
)
PARTITION BY RANGE (authorization_date_key);

-- Partition examples.
-- We can add more yearly partitions later as the project grows.

CREATE TABLE analytics.fact_transaction_analysis_2024
PARTITION OF analytics.fact_transaction_analysis
FOR VALUES FROM (20240101) TO (20250101);

CREATE TABLE analytics.fact_transaction_analysis_2025
PARTITION OF analytics.fact_transaction_analysis
FOR VALUES FROM (20250101) TO (20260101);

CREATE TABLE analytics.fact_transaction_analysis_2026
PARTITION OF analytics.fact_transaction_analysis
FOR VALUES FROM (20260101) TO (20270101);

CREATE TABLE analytics.fact_transaction_analysis_2027
PARTITION OF analytics.fact_transaction_analysis
FOR VALUES FROM (20270101) TO (20280101);

CREATE TABLE analytics.fact_transaction_analysis_default
PARTITION OF analytics.fact_transaction_analysis
DEFAULT;

-- Fact indexes for common analytics queries

CREATE INDEX idx_fact_authorization_date
ON analytics.fact_transaction_analysis (authorization_date_key);

CREATE INDEX idx_fact_merchant
ON analytics.fact_transaction_analysis (merchant_key);

CREATE INDEX idx_fact_card
ON analytics.fact_transaction_analysis (card_key);

CREATE INDEX idx_fact_acquiring_partner
ON analytics.fact_transaction_analysis (acquiring_partner_key);

CREATE INDEX idx_fact_region
ON analytics.fact_transaction_analysis (region_key);

CREATE INDEX idx_fact_current_category
ON analytics.fact_transaction_analysis (current_category_key);

CREATE INDEX idx_fact_optimal_category
ON analytics.fact_transaction_analysis (optimal_category_key);

CREATE INDEX idx_fact_source_transaction
ON analytics.fact_transaction_analysis (source_transaction_id);

CREATE INDEX idx_fact_transaction_mcc_code
ON analytics.fact_transaction_analysis (transaction_mcc_code);

-- =============================================================================
-- MATERIALIZED VIEW: Monthly fee savings
-- Used for dashboard totals by month.
-- =============================================================================
CREATE MATERIALIZED VIEW analytics.mv_monthly_fee_savings AS
SELECT
    d.year_number,
    d.month_number,
    d.month_name,

    COUNT(*) AS transaction_count,
    SUM(f.transaction_amount) AS total_transaction_amount,
    SUM(f.current_interchange_fee_amount) AS total_current_fee_amount,
    SUM(f.optimal_interchange_fee_amount) AS total_optimal_fee_amount,
    SUM(f.saving_amount) AS total_saving_amount,
    AVG(f.saving_percentage) AS avg_saving_percentage
FROM analytics.fact_transaction_analysis f
JOIN analytics.dim_date d
    ON d.date_key = f.authorization_date_key
GROUP BY
    d.year_number,
    d.month_number,
    d.month_name
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_monthly_fee_savings
ON analytics.mv_monthly_fee_savings (year_number, month_number);

-- =============================================================================
-- MATERIALIZED VIEW: Merchant optimization summary
-- Used to identify merchants with highest potential savings.
-- =============================================================================
CREATE MATERIALIZED VIEW analytics.mv_merchant_optimization_summary AS
SELECT
    m.merchant_key,
    m.source_merchant_id,
    m.merchant_name,
    m.mcc_code,
    m.mcc_description,

    COUNT(*) AS transaction_count,
    SUM(f.transaction_amount) AS total_transaction_amount,
    SUM(f.current_interchange_fee_amount) AS total_current_fee_amount,
    SUM(f.optimal_interchange_fee_amount) AS total_optimal_fee_amount,
    SUM(f.saving_amount) AS total_saving_amount,
    AVG(f.saving_percentage) AS avg_saving_percentage
FROM analytics.fact_transaction_analysis f
JOIN analytics.dim_merchant m
    ON m.merchant_key = f.merchant_key
GROUP BY
    m.merchant_key,
    m.source_merchant_id,
    m.merchant_name,
    m.mcc_code,
    m.mcc_description
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_merchant_optimization_summary
ON analytics.mv_merchant_optimization_summary (merchant_key);

-- =============================================================================
-- MATERIALIZED VIEW: Category transition summary
-- Used to show movement from current category to optimal category.
-- Example:
-- Ecom Non-Secure Credit -> Ecom Secure Preferred Credit
-- =============================================================================
CREATE MATERIALIZED VIEW analytics.mv_category_transition_summary AS
SELECT
    current_cat.category_key AS current_category_key,
    current_cat.category_name AS current_category_name,

    optimal_cat.category_key AS optimal_category_key,
    optimal_cat.category_name AS optimal_category_name,

    COUNT(*) AS transaction_count,
    SUM(f.current_interchange_fee_amount) AS total_current_fee_amount,
    SUM(f.optimal_interchange_fee_amount) AS total_optimal_fee_amount,
    SUM(f.saving_amount) AS total_saving_amount,
    AVG(f.saving_percentage) AS avg_saving_percentage
FROM analytics.fact_transaction_analysis f
JOIN analytics.dim_interchange_category current_cat
    ON current_cat.category_key = f.current_category_key
JOIN analytics.dim_interchange_category optimal_cat
    ON optimal_cat.category_key = f.optimal_category_key
GROUP BY
    current_cat.category_key,
    current_cat.category_name,
    optimal_cat.category_key,
    optimal_cat.category_name
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_category_transition_summary
ON analytics.mv_category_transition_summary (
    current_category_key,
    optimal_category_key
);