package com.example.api.ml.dto;

import java.util.List;

public record MlRecommendationRequest(

        // Current rule-engine result
        MlRuleEngineResult currentResult,

        // Optimization suggestions generated by rule engine/business logic
        List<MlRecommendationSuggestion> suggestions

) {}