from typing import Any, Dict, List, Optional
from pydantic import BaseModel
from datetime import datetime
from typing import Optional


class RuleEngineResult(BaseModel):
    category: str
    feeRate: float
    feeAmount: float
    transaction: Dict[str, Any]


class MissedCondition(BaseModel):
    condition: str
    currentValue: Optional[Any]
    optimalValue: Optional[Any]
    impact: float
    confidence: float
    explanation: str


class MissedConditionAnalysis(BaseModel):
    currentCategory: str
    optimalCategory: str
    currentFeeRate: float
    optimalFeeRate: float
    missedConditions: List[MissedCondition]

class ChangeSuggestion(BaseModel):
    # Short name of the suggested change
    suggestionType: str

    # Clear action the user should take
    action: str

    # Field that should be changed, for example "threeDS"
    field: str

    # Current value from the transaction
    currentValue: Optional[Any]

    # Recommended new value
    suggestedValue: Optional[Any]

    # Expected financial impact
    expectedImpact: float

    # How hard it is to apply this change
    difficulty: str

    # Human-readable explanation
    description: str


class ChangeSuggestionResponse(BaseModel):
    # List of suggestions sorted by financial impact
    suggestions: List[ChangeSuggestion]

class TransactionChange(BaseModel):
    # Name of the transaction field that was changed
    field: str

    # Value before the simulation
    originalValue: Optional[Any]

    # Value after applying the suggestion
    newValue: Optional[Any]

    # Type of suggestion that caused the change
    suggestionType: str

    # Explanation for why this change was applied
    reason: str


class TransactionSimulationRequest(BaseModel):
    # Original transaction received by the ML service
    transaction: Dict[str, Any]

    # Suggestions generated by the ChangeSuggestionEngine
    suggestions: List[ChangeSuggestion]


class TransactionSimulationResponse(BaseModel):
    # Original transaction preserved unchanged
    originalTransaction: Dict[str, Any]

    # Modified transaction after suggestions are applied
    simulatedTransaction: Dict[str, Any]

    # List of changes applied during simulation
    auditTrail: List[TransactionChange]

    # True if simulated transaction passes validation
    valid: bool

    # Validation errors or warnings
    validationMessages: List[str]

class MLCoreRequest(BaseModel):
    # Current result from Rule Engine Pass 1
    currentResult: RuleEngineResult

    # Optimal/mock result from Rule Engine Pass 2
    optimalResult: RuleEngineResult


class RankedSuggestion(ChangeSuggestion):
    # Final weighted score used for ranking
    score: float


class MLCoreResponse(BaseModel):
    # Missed condition analysis from Story 3.1
    analysis: MissedConditionAnalysis

    # Ranked suggestions from Story 3.2 + scoring algorithm
    rankedSuggestions: List[RankedSuggestion]

    # Simulated transaction from Story 3.3
    simulation: TransactionSimulationResponse

    # Common condition patterns found in this transaction
    detectedPatterns: Dict[str, Any]

    # Algorithm selected by the A/B testing layer
    algorithmUsed: str

class PortfolioPatternResponse(BaseModel):
    # Most frequently occurring missed condition across all transactions
    mostCommonCondition: Optional[str]

    # Condition that contributes the highest total financial impact
    highestImpactCondition: Optional[str]

    # Number of occurrences for each condition
    conditionFrequency: Dict[str, int]

    # Average impact per condition (mean savings opportunity)
    averageImpactByCondition: Dict[str, float]

    # Total potential savings aggregated per condition
    totalSavingsOpportunity: Dict[str, float]

class TransactionAnomaly(BaseModel):
    # Optional transaction identifier if available in transaction data
    transactionId: Optional[str]

    # Type of anomaly detected, for example FEE_OUTLIER
    anomalyType: str

    # Expected fee rate or expected value
    expectedFee: Optional[float]

    # Actual fee rate or actual value
    actualFee: Optional[float]

    # Difference between actual and expected value
    deviation: Optional[float]

    # Severity level: LOW, MEDIUM, HIGH
    severity: str

    # Human-readable explanation of why this was flagged
    explanation: str


class AnomalyDetectionResponse(BaseModel):
    # List of detected anomalies
    anomalies: List[TransactionAnomaly]

    # Warnings for skipped checks or missing fields
    warnings: List[str]

class BulkSimulationTransactionInput(BaseModel):
    # Current result from the rule engine for this transaction
    currentResult: RuleEngineResult

    # Optimal/mock result used to calculate missed conditions and recommendations
    optimalResult: RuleEngineResult


class BulkSimulationRequest(BaseModel):
    # List of transactions to simulate in bulk
    transactions: List[BulkSimulationTransactionInput]

    # Number of top ranked recommendations to apply per transaction
    applyTopNRecommendations: int = 2


class BulkSimulationSkippedTransaction(BaseModel):
    # Index of the transaction in the input list
    index: int

    # Reason why this transaction was skipped
    reason: str


class BulkSimulationResponse(BaseModel):
    # Sum of original/current fees for processed transactions
    totalCurrentFees: float

    # Sum of simulated fees after applying recommendations
    totalSimulatedFees: float

    # Difference between current and simulated fees
    totalSavings: float

    # Savings grouped by missed condition / suggestion type
    savingsByCondition: Dict[str, float]

    # Number of transactions successfully processed
    processedTransactions: int

    # Transactions skipped because they were invalid or failed processing
    skippedTransactions: List[BulkSimulationSkippedTransaction]

class RootCauseItem(BaseModel):
    # Missed condition that appears as a systemic optimization driver
    condition: str

    # Number of times this condition appears across the portfolio
    frequency: int

    # Sum of all impact values for this condition
    totalImpact: float

    # Average impact for this condition
    averageImpact: float

    # Ranking score used to order root causes
    score: float

    # Confidence level based on available data volume
    confidence: str

    # Human-readable explanation of the likely root cause
    rootCause: str

    # ML driver score from trained root-cause model
    mlDriverScore: Optional[float] = None

    # Final score combining heuristic score + ML driver score
    combinedScore: Optional[float] = None

    # ML model version used for root-cause evidence
    modelVersion: Optional[str] = None

    # ML explanation/evidence
    explanation: Optional[str] = None


class RootCauseAnalysisResponse(BaseModel):
    # Ranked list of likely root causes
    rootCauses: List[RootCauseItem]

    # Warnings for empty or low-quality input
    warnings: List[str]

class HistoricalMLRecord(BaseModel):
    transactionId: str
    timestamp: datetime
    features: Dict[str, Any]
    labels: Optional[Dict[str, Any]] = None
    currentRuleEngineResult: Dict[str, Any]
    optimalRuleEngineResult: Dict[str, Any]
    missedConditions: List[Dict[str, Any]]
    rankedSuggestions: List[Dict[str, Any]]
    simulatedSavings: Optional[float] = None
    actualOutcome: Optional[Dict[str, Any]] = None
    modelVersion: Optional[str] = None
    algorithmUsed: str


class HistoricalDataStoreResult(BaseModel):
    stored: bool
    transactionId: Optional[str]
    warnings: List[str]

class RecommendationPrioritizationRequest(BaseModel):
    currentResult: RuleEngineResult
    optimalResult: RuleEngineResult


class PrioritizedRecommendation(BaseModel):
    suggestionType: str
    action: str
    field: str
    currentValue: Optional[Any]
    suggestedValue: Optional[Any]
    expectedImpact: float
    difficulty: str
    description: str
    score: float
    priority: str
    rankingReason: str


class RecommendationPrioritizationResponse(BaseModel):
    recommendations: List[PrioritizedRecommendation]
    algorithmUsed: str
    modelVersion: Optional[str] = None
    fallbackUsed: bool
    warnings: List[str]

class AIReportTransactionInput(BaseModel):
    currentResult: RuleEngineResult
    optimalResult: RuleEngineResult


class AIReportRequest(BaseModel):
    transactions: List[AIReportTransactionInput]
    reportName: Optional[str] = "AI Optimization Report"


class AIReportSummary(BaseModel):
    reportName: str
    totalTransactions: int
    processedTransactions: int
    totalCurrentFees: float
    totalOptimizedFees: float
    estimatedSavings: float
    anomalyCount: int
    topRecommendation: Optional[str]
    topRootCause: Optional[str]


class AIReportRecommendationSummary(BaseModel):
    suggestionType: str
    count: int
    totalExpectedImpact: float
    averageScore: float
    priority: str
    explanation: str


class AIReportAnomalySummary(BaseModel):
    transactionId: Optional[str]
    anomalyType: str
    severity: str
    explanation: str


class AIReportRootCauseSummary(BaseModel):
    condition: str
    frequency: int
    totalImpact: float
    averageImpact: float
    score: float
    confidence: str
    rootCause: str
    mlDriverScore: Optional[float] = None
    combinedScore: Optional[float] = None
    modelVersion: Optional[str] = None
    explanation: Optional[str] = None


class AIReportResponse(BaseModel):
    reportId: str
    summary: AIReportSummary
    recommendationSummary: List[AIReportRecommendationSummary]
    anomalySummary: List[AIReportAnomalySummary]
    rootCauseSummary: List[AIReportRootCauseSummary]
    portfolioDrivers: Dict[str, Any]
    warnings: List[str]