from typing import Any, Dict, List, Optional
from pydantic import BaseModel


class RuleEngineResult(BaseModel):
    category: str
    feeRate: float
    feeAmount: float
    transaction: Dict[str, Any]


class MissedCondition(BaseModel):
    condition: str
    currentValue: Optional[Any]
    optimalValue: Optional[Any]
    impact: float
    confidence: float
    explanation: str


class MissedConditionAnalysis(BaseModel):
    currentCategory: str
    optimalCategory: str
    currentFeeRate: float
    optimalFeeRate: float
    missedConditions: List[MissedCondition]

class ChangeSuggestion(BaseModel):
    # Short name of the suggested change
    suggestionType: str

    # Clear action the user should take
    action: str

    # Field that should be changed, for example "threeDS"
    field: str

    # Current value from the transaction
    currentValue: Optional[Any]

    # Recommended new value
    suggestedValue: Optional[Any]

    # Expected financial impact
    expectedImpact: float

    # How hard it is to apply this change
    difficulty: str

    # Human-readable explanation
    description: str


class ChangeSuggestionResponse(BaseModel):
    # List of suggestions sorted by financial impact
    suggestions: List[ChangeSuggestion]

class TransactionChange(BaseModel):
    # Name of the transaction field that was changed
    field: str

    # Value before the simulation
    originalValue: Optional[Any]

    # Value after applying the suggestion
    newValue: Optional[Any]

    # Type of suggestion that caused the change
    suggestionType: str

    # Explanation for why this change was applied
    reason: str


class TransactionSimulationRequest(BaseModel):
    # Original transaction received by the ML service
    transaction: Dict[str, Any]

    # Suggestions generated by the ChangeSuggestionEngine
    suggestions: List[ChangeSuggestion]


class TransactionSimulationResponse(BaseModel):
    # Original transaction preserved unchanged
    originalTransaction: Dict[str, Any]

    # Modified transaction after suggestions are applied
    simulatedTransaction: Dict[str, Any]

    # List of changes applied during simulation
    auditTrail: List[TransactionChange]

    # True if simulated transaction passes validation
    valid: bool

    # Validation errors or warnings
    validationMessages: List[str]

class MLCoreRequest(BaseModel):
    # Current result from Rule Engine Pass 1
    currentResult: RuleEngineResult

    # Optimal/mock result from Rule Engine Pass 2
    optimalResult: RuleEngineResult


class RankedSuggestion(ChangeSuggestion):
    # Final weighted score used for ranking
    score: float


class MLCoreResponse(BaseModel):
    # Missed condition analysis from Story 3.1
    analysis: MissedConditionAnalysis

    # Ranked suggestions from Story 3.2 + scoring algorithm
    rankedSuggestions: List[RankedSuggestion]

    # Simulated transaction from Story 3.3
    simulation: TransactionSimulationResponse

    # Common condition patterns found in this transaction
    detectedPatterns: Dict[str, Any]

    # Algorithm selected by the A/B testing layer
    algorithmUsed: str